In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('play_football_dataset.csv')

In [4]:
df

          Day Weather Temperature Humidity    Wind Play Football?
0       Day 1  Cloudy         Hot     High    Weak            Yes
1       Day 2  Cloudy        Mild     High    Weak            Yes
2       Day 3    Rain        Cool   Normal  Strong             No
3       Day 4   Sunny        Mild   Normal  Strong            Yes
4       Day 5   Sunny         Hot     High  Strong             No
..        ...     ...         ...      ...     ...            ...
995   Day 996    Rain        Mild   Normal    Weak            Yes
996   Day 997    Rain        Mild   Normal  Strong             No
997   Day 998   Sunny        Mild   Normal  Strong            Yes
998   Day 999   Sunny        Mild   Normal  Strong            Yes
999  Day 1000   Sunny         Hot     High    Weak             No

[1000 rows x 6 columns]

In [5]:
X = df.drop(columns='Play Football?', axis=1)

In [6]:
X = df.drop(columns=['Day', 'Play Football?'], axis=1)

In [7]:
X

    Weather Temperature Humidity    Wind
0    Cloudy         Hot     High    Weak
1    Cloudy        Mild     High    Weak
2      Rain        Cool   Normal  Strong
3     Sunny        Mild   Normal  Strong
4     Sunny         Hot     High  Strong
..      ...         ...      ...     ...
995    Rain        Mild   Normal    Weak
996    Rain        Mild   Normal  Strong
997   Sunny        Mild   Normal  Strong
998   Sunny        Mild   Normal  Strong
999   Sunny         Hot     High    Weak

[1000 rows x 4 columns]

In [8]:
y = df['Play Football?']

In [9]:
y

0      Yes
1      Yes
2       No
3      Yes
4       No
      ...
995    Yes
996     No
997    Yes
998    Yes
999     No
Name: Play Football?, Length: 1000, dtype: object

In [12]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
X_encoded = encoder.fit_transform(X)
X_encoded

array([[0., 1., 0., 1.],
       [0., 2., 0., 1.],
       [1., 0., 1., 0.],
       ...,
       [2., 2., 1., 0.],
       [2., 2., 1., 0.],
       [2., 1., 0., 1.]], shape=(1000, 4))

In [13]:
y_encoded = y.map({ 'Yes':1 , 'No':0})

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y_encoded, test_size=0.3)

In [23]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [24]:
model.score(X_test, y_test)

0.96

In [25]:
from joblib import load, dump
dump(model, 'decisiontree.joblib')

['decisiontree.joblib']

In [ ]:
model.predict([1,2,3,1])

ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 3. 1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.